export interface Stock {
  id: string;
  symbol: string;
  name: string;
  country: string;
  marketCap: number;
  price: number;
  changes: number;
  changesPercentage: number;
  monthlyChanges: number;
  monthlyChangesPercentage: number;
  indexes: string[];
  lastUpdated: string;
}

export const MOCK_STOCKS_DATA: Stock[] = [
  {
    id: 'AAPL',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    country: 'USA',
    marketCap: 3000000000000,
    price: 150.25,
    changes: 2.15,
    changesPercentage: 1.45,
    monthlyChanges: 8.25,
    monthlyChangesPercentage: 5.82,
    indexes: ['NASDAQ', 'S&P500'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'MSFT',
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    country: 'USA',
    marketCap: 2800000000000,
    price: 375.5,
    changes: -1.25,
    changesPercentage: -0.33,
    monthlyChanges: -5.8,
    monthlyChangesPercentage: -1.52,
    indexes: ['NASDAQ', 'S&P500'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'GOOGL',
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    country: 'USA',
    marketCap: 1800000000000,
    price: 142.8,
    changes: 0.95,
    changesPercentage: 0.67,
    monthlyChanges: 4.2,
    monthlyChangesPercentage: 3.03,
    indexes: ['NASDAQ', 'S&P500'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'AMZN',
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    country: 'USA',
    marketCap: 1500000000000,
    price: 155.3,
    changes: -2.1,
    changesPercentage: -1.33,
    monthlyChanges: -8.5,
    monthlyChangesPercentage: -5.19,
    indexes: ['NASDAQ', 'S&P500'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'TSLA',
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    country: 'USA',
    marketCap: 800000000000,
    price: 245.75,
    changes: 5.2,
    changesPercentage: 2.16,
    monthlyChanges: 15.8,
    monthlyChangesPercentage: 6.87,
    indexes: ['NASDAQ', 'S&P500'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'NVDA',
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    country: 'USA',
    marketCap: 1200000000000,
    price: 485.6,
    changes: 12.3,
    changesPercentage: 2.6,
    monthlyChanges: 45.2,
    monthlyChangesPercentage: 10.26,
    indexes: ['NASDAQ', 'S&P500'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'META',
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    country: 'USA',
    marketCap: 900000000000,
    price: 320.45,
    changes: -3.15,
    changesPercentage: -0.97,
    monthlyChanges: -12.5,
    monthlyChangesPercentage: -3.75,
    indexes: ['NASDAQ', 'S&P500'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'NFLX',
    symbol: 'NFLX',
    name: 'Netflix Inc.',
    country: 'USA',
    marketCap: 200000000000,
    price: 485.2,
    changes: 1.85,
    changesPercentage: 0.38,
    monthlyChanges: 8.5,
    monthlyChangesPercentage: 1.78,
    indexes: ['NASDAQ', 'S&P500'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'AMD',
    symbol: 'AMD',
    name: 'Advanced Micro Devices',
    country: 'USA',
    marketCap: 250000000000,
    price: 155.4,
    changes: 2.75,
    changesPercentage: 1.8,
    monthlyChanges: 12.3,
    monthlyChangesPercentage: 8.6,
    indexes: ['NASDAQ', 'S&P500'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'INTC',
    symbol: 'INTC',
    name: 'Intel Corporation',
    country: 'USA',
    marketCap: 180000000000,
    price: 45.25,
    changes: -0.85,
    changesPercentage: -1.85,
    monthlyChanges: -3.2,
    monthlyChangesPercentage: -6.6,
    indexes: ['NASDAQ', 'S&P500'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'CRM',
    symbol: 'CRM',
    name: 'Salesforce Inc.',
    country: 'USA',
    marketCap: 220000000000,
    price: 225.8,
    changes: 1.2,
    changesPercentage: 0.53,
    monthlyChanges: 5.8,
    monthlyChangesPercentage: 2.64,
    indexes: ['NYSE', 'S&P500'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'ADBE',
    symbol: 'ADBE',
    name: 'Adobe Inc.',
    country: 'USA',
    marketCap: 280000000000,
    price: 580.9,
    changes: -4.25,
    changesPercentage: -0.73,
    monthlyChanges: -15.2,
    monthlyChangesPercentage: -2.55,
    indexes: ['NASDAQ', 'S&P500'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'ORCL',
    symbol: 'ORCL',
    name: 'Oracle Corporation',
    country: 'USA',
    marketCap: 320000000000,
    price: 115.65,
    changes: 0.95,
    changesPercentage: 0.83,
    monthlyChanges: 3.8,
    monthlyChangesPercentage: 3.39,
    indexes: ['NYSE', 'S&P500'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'ASML',
    symbol: 'ASML',
    name: 'ASML Holding N.V.',
    country: 'Netherlands',
    marketCap: 350000000000,
    price: 875.5,
    changes: 8.25,
    changesPercentage: 0.95,
    monthlyChanges: 25.8,
    monthlyChangesPercentage: 3.04,
    indexes: ['AEX'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'SAP',
    symbol: 'SAP',
    name: 'SAP SE',
    country: 'Germany',
    marketCap: 180000000000,
    price: 155.8,
    changes: -1.45,
    changesPercentage: -0.92,
    monthlyChanges: -5.2,
    monthlyChangesPercentage: -3.23,
    indexes: ['DAX'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'NOVN.SW',
    symbol: 'NOVN.SW',
    name: 'Novartis AG',
    country: 'Switzerland',
    marketCap: 200000000000,
    price: 95.25,
    changes: 0.75,
    changesPercentage: 0.79,
    monthlyChanges: 2.8,
    monthlyChangesPercentage: 3.02,
    indexes: ['SMI'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'NESN.SW',
    symbol: 'NESN.SW',
    name: 'Nestlé S.A.',
    country: 'Switzerland',
    marketCap: 320000000000,
    price: 115.4,
    changes: -0.85,
    changesPercentage: -0.73,
    monthlyChanges: -2.5,
    monthlyChangesPercentage: -2.12,
    indexes: ['SMI'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'TSM',
    symbol: 'TSM',
    name: 'Taiwan Semiconductor Manufacturing',
    country: 'Taiwan',
    marketCap: 550000000000,
    price: 105.75,
    changes: 2.15,
    changesPercentage: 2.08,
    monthlyChanges: 8.5,
    monthlyChangesPercentage: 8.74,
    indexes: ['TWSE'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'BABA',
    symbol: 'BABA',
    name: 'Alibaba Group Holding Limited',
    country: 'China',
    marketCap: 180000000000,
    price: 85.5,
    changes: -1.25,
    changesPercentage: -1.44,
    monthlyChanges: -5.8,
    monthlyChangesPercentage: -6.35,
    indexes: ['NYSE'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'JD',
    symbol: 'JD',
    name: 'JD.com Inc.',
    country: 'China',
    marketCap: 45000000000,
    price: 28.75,
    changes: 0.45,
    changesPercentage: 1.59,
    monthlyChanges: 1.8,
    monthlyChangesPercentage: 6.67,
    indexes: ['NASDAQ'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'NIO',
    symbol: 'NIO',
    name: 'NIO Inc.',
    country: 'China',
    marketCap: 12000000000,
    price: 8.25,
    changes: -0.15,
    changesPercentage: -1.79,
    monthlyChanges: -0.8,
    monthlyChangesPercentage: -8.84,
    indexes: ['NYSE'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'XPEV',
    symbol: 'XPEV',
    name: 'XPeng Inc.',
    country: 'China',
    marketCap: 8000000000,
    price: 12.4,
    changes: 0.35,
    changesPercentage: 2.9,
    monthlyChanges: 1.5,
    monthlyChangesPercentage: 13.76,
    indexes: ['NYSE'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'LI',
    symbol: 'LI',
    name: 'Li Auto Inc.',
    country: 'China',
    marketCap: 15000000000,
    price: 18.9,
    changes: 0.85,
    changesPercentage: 4.71,
    monthlyChanges: 3.2,
    monthlyChangesPercentage: 20.37,
    indexes: ['NASDAQ'],
    lastUpdated: new Date().toISOString(),
  },
];
